name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Copy files
      run: |
        ls | more
        cp ./js/rpc-interface.js ./docs/rpc-interface.js
