name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Copy files
      run: |
        cp ./js/rpc-interface.js ./docs/rpc-interface.js
        cp ./js/movi-interface.js ./docs/movi-interface.js
        cp ./js/pako.mod.js ./docs/pako.mod.js
      
