name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Copy files
      run: |
        cp ./js/rpc-interface.js ./docs/rpc-interface.js
        cp ./js/movi-interface.js ./docs/movi-interface.js
        cp ./js/pako.mod.js ./docs/pako.mod.js
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
